# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField()),
                ('productName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Category', models.CharField(max_length=20)),
                ('CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
