# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productapply_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductApply',
            new_name='UserProduct',
        ),
    ]
