# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-27 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190226_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ufile',
            new_name='Profile',
        ),
    ]
