# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190227_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPic',
            field=models.FileField(blank=True, default='account/images/NonameUser.jpg', upload_to='account/images'),
        ),
    ]
