# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-26 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20181224_1628'),
        ('store', '0006_auto_20190130_1527'),
    ]

    operations = [
    ]
